import importlib.util
from pathlib import Path
from types import ModuleType
from typing import Optional


def _is_laneatt_config(source_cfg: Path) -> bool:
    module = load_config_module(source_cfg)
    try:
        return str(module.heads["type"]) == "LaneATT"
    except (AttributeError, KeyError, TypeError):
        return False


def write_runtime_config(
    *,
    source_cfg: Path,
    target_cfg: Path,
    lanedet_root: Path,
    dataset_root: Optional[Path],
    batch_size: Optional[int],
    epochs: Optional[int],
    workers: Optional[int],
) -> Path:
    """Write a patched runtime config that points LaneDet to project paths and options."""
    text = source_cfg.read_text(encoding="utf-8")
    target_cfg.parent.mkdir(parents=True, exist_ok=True)

    overrides = [
        "",
        "# Project runtime overrides generated by tools/lanedet.",
    ]
    anchors_path = lanedet_root / ".cache" / "tusimple_anchors_freq.pt"
    if anchors_path.exists() and _is_laneatt_config(source_cfg):
        overrides.append(f"heads['anchors_freq_path'] = {str(anchors_path)!r}")
    if dataset_root is not None:
        overrides.extend(
            [
                f"dataset_path = {str(dataset_root)!r}",
                f"test_json_file = {str(dataset_root / 'test_label.json')!r}",
            ]
        )
    if batch_size is not None:
        overrides.append(f"batch_size = {int(batch_size)}")
    if epochs is not None:
        overrides.append(f"epochs = {int(epochs)}")
    if workers is not None:
        overrides.append(f"workers = {int(workers)}")

    if dataset_root is not None:
        overrides.extend(
            [
                "dataset['train']['data_root'] = dataset_path",
                "dataset['val']['data_root'] = dataset_path",
                "dataset['test']['data_root'] = dataset_path",
                "",
            ]
        )

    target_cfg.write_text(text + "\n".join(overrides), encoding="utf-8")
    return target_cfg


def load_config_module(config_path: Path) -> ModuleType:
    """Import a LaneDet config file as a Python module."""
    spec = importlib.util.spec_from_file_location("_lanedet_runtime_config", config_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not load config: {config_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def dataset_family_from_config(config_path: Path) -> str:
    """Infer the LaneDet dataset family from a config file."""
    module = load_config_module(config_path)
    try:
        dataset_type = module.dataset["train"]["type"]
    except (AttributeError, KeyError, TypeError) as exc:
        raise ValueError(f"Could not read dataset.train.type from {config_path}") from exc
    return str(dataset_type).lower()
