from pathlib import Path
from typing import Optional


def write_runtime_config(
    *,
    source_cfg: Path,
    target_cfg: Path,
    lanedet_root: Path,
    dataset_root: Optional[Path],
    batch_size: Optional[int],
    epochs: Optional[int],
    workers: Optional[int],
) -> Path:
    text = source_cfg.read_text(encoding="utf-8")
    target_cfg.parent.mkdir(parents=True, exist_ok=True)

    overrides = [
        "",
        "# Project runtime overrides generated by tools/lanedet.",
    ]
    anchors_path = lanedet_root / ".cache" / "tusimple_anchors_freq.pt"
    if anchors_path.exists():
        overrides.append(f"heads['anchors_freq_path'] = {str(anchors_path)!r}")
    if dataset_root is not None:
        overrides.extend(
            [
                f"dataset_path = {str(dataset_root)!r}",
                f"test_json_file = {str(dataset_root / 'test_label.json')!r}",
            ]
        )
    if batch_size is not None:
        overrides.append(f"batch_size = {int(batch_size)}")
    if epochs is not None:
        overrides.append(f"epochs = {int(epochs)}")
    if workers is not None:
        overrides.append(f"workers = {int(workers)}")

    if dataset_root is not None:
        overrides.extend(
            [
                "dataset['train']['data_root'] = dataset_path",
                "dataset['val']['data_root'] = dataset_path",
                "dataset['test']['data_root'] = dataset_path",
                "",
            ]
        )

    target_cfg.write_text(text + "\n".join(overrides), encoding="utf-8")
    return target_cfg
